version: "3.8"

# Microservicios de la aplicación

services:
# Microservicio de manejo de boletos
  boletos:
    build:
      context: ./services/boleto.api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
# Microservicio de manejo del notificaciones.
  notificaciones:
    build:
      context: ./services/notificaion.api
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
# Microservicio de manejo de suscripciones a boletos en billetera virtual.
  suscripciones:
    build:
      context: ./services/suscripcion.api
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
