name: .NET Test

on:
    workflow_dispatch:
        inputs:
          logLevel:
            description: 'Log level'
            required: true
            default: 'warning'
            type: choice
            options:
            - info
            - warning
            - debug
          tags:
            description: 'Test scenario tags'
            required: false
            type: boolean
          environment:
            description: 'Environment to run tests against'
            type: environment
            required: false
    pull_request:
        types:
            - opened
            - synchronize

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4.1.2

            - name: Setup .NET
              uses: actions/setup-dotnet@v2
              with:
                    dotnet-version: '7.0.x'

            - name: Restore dependencies
              run: dotnet restore '/app/Flecha Digital/Flecha Digital.csproj'

            - name: Build and test
              run: dotnet build --configuration Debug --no-restore
              continue-on-error: true

            - name: Run tests
              run: dotnet test --no-restore --verbosity normal

            - name: Run unit tests
              run: dotnet test --no-restore --verbosity normal --filter Category=Unit

            - name: Run integration tests
              run: dotnet test --no-restore --verbosity normal --filter Category=Integration

            - name: Check test results
              run: |
                    if [ ${{ job.status }} == 'success' ]; then
                        echo "Tests passed. Pull request can proceed."
                    else
                        echo "Tests failed. Pull request cannot proceed."
                        exit 1
                    fi
