name: JavaScript Tests

on:
    workflow_dispatch:
        inputs:
          logLevel:
            description: 'Log level'
            required: true
            default: 'warning'
            type: choice
            options:
            - info
            - warning
            - debug
          tags:
            description: 'Test scenario tags'
            required: false
            type: boolean
          environment:
            description: 'Environment to run tests against'
            type: environment
            required: true
    pull_request:
        types: 
            - opened
            - synchronize

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4.1.2

            - name: Install Node.js
              uses: actions/setup-node@v4.0.2
              with:
                    node-version: '20.11.1'

            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npm test

            - name: Validate tests
              run: |
                    if [ ${{ job.status }} == 'success' ]; then
                        echo "Tests passed. Proceeding with the pull request."
                    else
                        echo "Tests failed. The pull request will not be allowed."
                        exit 1
                    fi
